---
Name: accessibility-config
---
Iliain\Accessible\ShortcodeProviders\AccImageShortcodeProvider:
  custom_template: 'Iliain\\Accessible\\Shortcodes\\Image'        # (String|null) Custom template 

Iliain\Accessible\ShortcodeProviders\AccLinkShortcodeProvider:
  custom_template: 'Iliain\\Accessible\\Shortcodes\\Link'         # (String|null) Custom template 
