---
Name: accessibility-config
---
Iliain\Accessible\Config:
    settings:
      enable_image_shortcode: true # (Boolean) Enable the image shortcode feature
      enable_link_shortcode: true # (Boolean) Enable the link shortcode feature
    customise:
      image_shortcode_template: 'Iliain\Accessible\Includes\AccessibleShortcodeImage' # (String) Template to use for the image shortcode
      link_shortcode_template: 'Iliain\Accessible\Includes\AccessibleShortcodeLink' # (String) Template to use for the link shortcode
